version: "3.8"
services:
  app:
    image: fastapi_social_network
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:psqldevpass@postgres/postgres"
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:14-alpine
    volumes:
      - fastapi-psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: psqldevpass

volumes:
  fastapi-psql-data:
